name: daikhopk
description: Daikho PK Application Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.4+5

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.2
  cached_network_image: ^3.0.0
  provider: ^5.0.0
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  firebase_messaging: ^9.1.3
  firebase_messaging_web: ^1.0.6
  google_sign_in: ^5.0.2
  apple_sign_in: ^0.1.0
  flutter_facebook_auth: ^3.3.3+1
  shared_preferences: ^2.0.5
  youtube_player_iframe: ^2.0.0
  url_launcher: ^6.0.0
  flutter_conditional_rendering: ^2.0.0
  flutter_swiper: ^1.1.6
  flappy_search_bar: ^1.7.2
  number_display: ^3.0.0
  flutter_staggered_grid_view: ^0.3.0
  line_awesome_flutter: ^1.0.1
  intl: ^0.17.0
  rate_my_app: ^1.1.0+1
  string_similarity: ^2.0.0
  responsive_framework: ^0.1.0
  android_intent: ^2.0.0
  flutter_local_notifications: ^5.0.0+3
  flutter_inappwebview: ^5.3.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.0"
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path_ios: 'assets/logo/daikho_icon_blackbgsquare.png'
  image_path_android: 'assets/logo/daikho_icon_blackbgsquare.png'
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/images/
  #  - assets/
  #  - images/a_dot_ham.jpeg
  #  - images/a_dot_burr.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
